name: Convert Notebook

on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Convert to HTML
      run: |
        pip install nbconvert
        jupyter nbconvert --to html main.ipynb
        
    - name: Upload HTML
      uses: actions/upload-artifact@v4
      with:
        name: notebook-html
        path: main.html